FROM python:3.10.12

WORKDIR /app

COPY /requirements.celery.txt .

RUN pip install -r requirements.celery.txt --no-cache-dir

COPY /. .

CMD ["celery", "-A", "predictor.core.celery", "worker", "-B"]
