version: '3'

volumes:
  pg_data:
  static:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  load_balancer:
    image: willageg/lct_load_balancer
    depends_on:
      - "accounts"
      - "parser"
    ports:
      - 9000:80
  accounts:
    image: willageg/lct_accounts
    env_file: .env
    volumes:
      - static:/app/collected_static
  parser:
    image: willageg/lct_parser
    env_file: .env
  predictor:
    build: willageg/lct_predictor
    env_file: .env
  redis:
    image: redis:latest
    ports:
     - 6379:6379
    restart: on-failure
  celery_predictor:
    build: willageg/lct_celery_predictor
    env_file: .env
    restart: on-failure