version: '3'

volumes:
  pg_data:
  static:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  load_balancer:
    build: ./services/load_balancer/
    depends_on:
      - 'accounts'
      - 'parser'
    ports:
      - 9000:80
  accounts:
    build: ./services/accounts/
    env_file: .env
    volumes:
      - static:/app/collected_static
  parser:
    build: ./services/parser/
    env_file: .env
  predictor:
    build:
      context: ./services/predictor
      dockerfile: ./Dockerfile
    env_file: .env
  redis:
    image: redis:latest
    ports:
     - 6379:6379
    restart: on-failure
  celery_predictor:
    build:
      context: ./services/predictor
      dockerfile: ./Dockerfile-celery
    env_file: .env
    restart: on-failure
