version: '3'

volumes:
  pg_data:
  static:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  load_balancer:
    image: willageg/lct_load_balancer
    volumes:
      - static:/staticfiles
    depends_on:
      - 'accounts'
      - 'parser'
    ports:
      - 9000:80
  frontend:
    image: willageg/lct_frontend
    volumes:
      - static:/frontend_static
  accounts:
    image: willageg/lct_accounts
    env_file: .env
    volumes:
      - static:/app/collected_static
  parser:
    image: willageg/lct_parser
    env_file: .env
  predictor:
    image: willageg/lct_predictor
    env_file: .env
  redis:
    image: redis:latest
    restart: on-failure
  celery_accounts:
    image: willageg/lct_celery_accounts
    env_file: .env
    restart: on-failure
    depends_on:
      - redis
