version: '3'

volumes:
  pg_data:
  static:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  accounts:
    build: ./services/accounts/
    env_file: .env
    volumes:
      - static:/app/collected_static
  load_balancer:
    build: ./services/load_balancer/
    depends_on:
      - "accounts"
    ports:
      - 9000:80
